services:
  fastapi:
      image: timbrown5/fastapi:v1
      build: 
        context: .
        dockerfile: Dockerfile
      ports:
      - 8000:8000


  streamlit:
      image: timbrown5/streamlit:v1
      build: 
        context: ./streamlit_app
        dockerfile: Dockerfile
      ports:
      - 8501:8501
      environment:
        API_URL: http://fastapi:8000
