name: MLOps CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11.5'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run Data processing steps
        run: |
          python src/data/run_processing.py \
            --input data/raw/house_data.csv \
            --output data/processed/cleaned_house_data.csv
          
      - name: Do feature engineering
        run: |
          python src/features/engineer.py \
            --input data/processed/cleaned_house_data.csv \
            --output data/processed/featured_house_data.csv \
            --preprocessor models/trained/preprocessor.pkl \
          
      - name: Start MLFLow
        run: |
          docker run --rm -d -p 5555:5555 --name mlflow-server ghcr.io/mlflow/mlflow:latest \
            mlflow server --host 0.0.0.0 \
            --backend-store-uri sqlite:///mlflow.db \
            --default-artifact-root /tmp/mlruns

      - name: Train model
        run: |
          python src/models/train_model.py \
            --config configs/models_config.yaml \
            --data data/processed/featured_house_data.csv \
            --models-dir models/
            --mlflow-tracking-uri http://localhost:5555

      - name: Start MLFLow
        run: |
          docker stop mlflow-server
          docker rm mlflow-server

          
